name = "PathCompleteCertificates"
uuid = "b391c707-6ba7-482f-97f4-86d517cfbcc9"
version = "0.1.0-DEV"
authors = ["Léa Ninite <lea.ninite@uclouvain.be>", "Julien Calbert <julien.calbert@uclouvain.be>", "Raphaël M. Jungers <raphael.jungers@uclouvain.be>"]

[deps]
HybridSystems = "2207ec0c-686c-5054-b4d2-543502888820"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathematicalSystems = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
HybridSystems = "0.4"
JuMP = "1"
LinearAlgebra = "1"
MathematicalSystems = "0.14"
Random = "1"
MultivariatePolynomials = "0.5"
RecipesBase = "1"
SumOfSquares = "0.7"
julia = "1.10"

[weakdeps]
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SumOfSquares = "4b9e565b-77fc-50a5-a571-1244f986bda1"

[extensions]
PathCompleteCertificatesRecipesBaseExt = "RecipesBase"
PathCompleteCertificatesSumOfSquaresExt = ["SumOfSquares", "MultivariatePolynomials"]
